---
title: "Basketball Analytics"
author: "Lucas Wu"
date: "February 21, 2017"
output:
  html_document:
    #toc: true
    #toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```


```{r, include=FALSE}
if (!require("dplyr")) install.packages('dplyr')
if (!require("DT")) install.packages('DT')
# library(dplyr)
# library(DT)
```

```{r,cache=TRUE,include=F}
load("all_data_clean.rdata")
```

```{r,function,include=F}
round_df <- function(df, digits) {
  nums <- vapply(df, is.numeric, FUN.VALUE = logical(1))
  df[,nums] <- round(df[,nums], digits = digits)
  (df)
}

```


```{r,include=FALSE}
# D2
D2 <- all_data_clean %>% filter(Division == "D2")

# gnac
gnac_team_name <- c("Alas. Anchorage",
                    "Alas. Fairbanks",
                    "Central Wash.",
                    "Concordia Portland",
                    "Mont. St. Billings",
                    "Northwest Nazarene",
                    "Saint Martin's",
                    "Seattle Pacific",
                    "Simon Fraser",
                    "Western Ore.",
                    "Western Wash.")

gnac <- D2 %>% filter(Team %in% gnac_team_name)

# change the type from char to numeric from column FGM to Fouls 
gnac <-  gnac %>% mutate_at(vars(FGM:Fouls),as.numeric)


# set NA to 0 from column FGM to Fouls
gnac[,14:29][is.na(gnac[,14:29])] <- 0

player_db_gnac <- gnac %>%  filter(Player != "TEAM",
                                 Player != "Totals",
                                 Player != "Team")


# calculate the mean and max of each metric
# apply(as.matrix(player_db_gnac[,14:29]), 2, mean)
# apply(as.matrix(player_db_gnac[,14:29]), 2, max)

player_stat_gnac_raw <- gnac %>% 
          # select Player,Season and other box-score stats 
          select(Player,Season,MP:Fouls) %>%
          # exclude team level stats
          filter(Player != "TEAM",
                 Player != "Totals",
                 Player != "Team") %>% 
          group_by_("Player","Season") %>% 
          summarise_all(.funs = c(Avg="mean", Total="sum"))

player_stat_gnac_added <- player_stat_gnac_raw %>% 
                          mutate( GP   = `FGM_Total`/FGM_Avg ,
                                  `2FGM_Total`= FGM_Total-`3FG_Total`     ,
                                 `2FGA_Total`= FGA_Total-`3FGA_Total`    ,
                                 `2FGM_Avg`= `2FGM_Total`/GP   ,
                                 `2FGA_Avg`= `2FGA_Total`/GP   ,
                                 `2FG%`   = `2FGM_Total`/`2FGA_Total` ,
                                 `3FG%`   = `3FG_Total`/`3FGA_Total`  ,
                                 `FT%`    = FT_Total/FTA_Total        ,
                                  POSS      = (FGA_Total + 0.44*FTA_Total + TO_Total),
                                  POSS_PG   = (FGA_Total + 0.44*FTA_Total + TO_Total) / (GP),
                                  PPP       = PTS_Total/POSS, 
                                  `TOV%`    = TO_Total/POSS,
                                  `TS%`     = PTS_Total/(2*(FGA_Total+0.44*FTA_Total)),
                                  `AST/TO`   = AST_Total/TO_Total,
                                  Win_Score  = ((PTS_Total + `Tot Reb_Total` + STL_Total + 0.5 * AST_Total) + (0.5 * BLK_Total) - (FGA_Total) - TO_Total - 0.5 * FT_Total - 0.5 * Fouls_Total)/(GP)
                                 )

# convert NaN into 0
is.nan.data.frame <- function(x)
  do.call(cbind, lapply(x, is.nan))
player_stat_gnac_added[is.nan(player_stat_gnac_added)] <- 0

# convert Inf into 0
is.infinite.data.frame <- function(x)
  do.call(cbind, lapply(x, is.infinite))
player_stat_gnac_added[is.infinite(player_stat_gnac_added)] <- 0 

```

```{r rename_box_score,echo=F}

player_stat_gnac_added <- player_stat_gnac_added %>% select(Player:Fouls_Avg, 
                                                GP, 
                                                `2FGM_Avg`:`Win_Score`)

renames <- c("Player", "Season"  ,"MIN",   "FGM"  , "FGA"  ,  "3FGM"  , "3FGA"  ,  "FT"  ,  "FTA"  ,  "PTS"  ,  "OREB" , "DREB", "TREB" , "AST"  ,   "TOV"    ,  "STL"  , "BLK" ,  "PF" , "GP", "2FGM", "2FGA", "2FG%", "3FG%", "FT%", "POSS", "POSS_PG", "PPP", "TOV%","TS%","AST/TO","Win_Score")

colnames(player_stat_gnac_added) <- renames


```


## GNAC Player Averages

```{r,echo=F,warning=F}
avg_by_year <- player_stat_gnac_added %>% group_by_("Season") %>% 
                      summarise_all(.funs = c(GNAC="mean"))

avg_by_year <- avg_by_year %>% select(-Player_GNAC)

avg_by_year$Season <- as.factor(avg_by_year$Season)

avg_renames <- c("Season"  ,"MIN",   "FGM"  , "FGA"  ,  "3FGM"  , "3FGA"  ,  "FT"  ,  "FTA"  ,  "PTS"  ,  "OREB" , "DREB", "TREB" , "AST"  ,   "TOV"    ,  "STL"  , "BLK" ,  "PF" , "GP", "2FGM", "2FGA", "2FG%", "3FG%", "FT%", "POSS", "POSS_PG", "PPP", "TOV%","TS%","AST/TO","Win_Score")

colnames(avg_by_year) <- avg_renames

avg_by_year <- round_df(avg_by_year,3)

DT:::datatable(    
              data = avg_by_year, 
              #filter = 'top', 
              rownames = FALSE,
              extensions = 'FixedColumns',
                                
              options = list
              (
                searchHighlight = TRUE,
                search = list(regex = TRUE, caseInsensitive = TRUE),
                pageLength = 10 ,
                autoWidth = TRUE,
                scrollX = TRUE,
                fixedColumns = list(leftColumns = 1)
              )
          ) %>% 
              formatPercentage(c('TS%',"2FG%", "3FG%", "FT%", "TOV%"), 1)  %>% 
              formatRound(c(2:30), 2)

```



## Player Box Score

#### Player Box Score Average Per Game (2012-2017)

```{r box_score,echo=F}
player_box <- player_stat_gnac_added %>% select(Player:`FT%`)
                                          
join_box <- left_join(player_box,(gnac %>% select(Player,Team)),by="Player",copy = FALSE)
player_box <- join_box[!duplicated(left_join(player_box,(gnac %>% select(Player,Team)),by="Player",copy = FALSE)),]


player_box$Season <- as.factor(player_box$Season)
player_box$Team <- as.factor(player_box$Team)
player_box <- round_df(player_box,3)

player_box_reorder <- player_box %>% select(Player, Team, Season, GP,
                                    MIN, PTS, TREB,
                                    AST,STL,BLK,
                                    `2FGM`,`2FGA`,`2FG%`,
                                    `3FGM`,`3FGA`,`3FG%`,
                                    `FT`,`FTA`,`FT%`,
                                    OREB,DREB,TOV,PF)
                                    

DT:::datatable(    data = player_box_reorder, 
              filter = 'top', 
              rownames = FALSE,
              #colnames = box_new_names,
              extensions = 'FixedColumns',
              
              options = list
              (
                searchHighlight = TRUE,
                search = list(regex = TRUE, caseInsensitive = TRUE),
                pageLength = 10,
                autoWidth = TRUE,
                scrollX = TRUE,
                fixedColumns = list(leftColumns = 1)
              )
          ) %>% 
              formatPercentage(c("2FG%", "3FG%", "FT%"), 1) %>% 
              formatRound(c(5:23), 2)

```

## Advanced Box Score

#### Advanced Box Score Average Per Game (2012-2017)


```{r advanced,echo=F}

join_player_adv_box <- left_join(player_stat_gnac_added,gnac %>% 
                              select(Player,Team),by="Player") %>% 
                                    select(Player, Team,
                                                    Season,
                                                    GP,
                                                    MIN,
                                                    PTS,
                                                    POSS,
                                                    POSS_PG,
                                                     PPP,
                                                    `TS%`,
                                                    `2FG%`,
                                                    `3FG%`,
                                                    `FT%`,
                                                    `AST/TO`,
                                                    Win_Score)


player_adv_box <- join_player_adv_box[!duplicated(join_player_adv_box),]


player_adv_box$Season <- as.factor(player_adv_box$Season)
player_adv_box$Team <- as.factor(player_adv_box$Team)
player_adv_box <- round_df(player_adv_box,3)

DT:::datatable(    data = player_adv_box, 
              filter = 'top', 
              rownames = FALSE,
              extensions = 'FixedColumns',
              options = list
              (
                searchHighlight = TRUE,
                search = list(regex = TRUE, caseInsensitive = TRUE),
                pageLength = 10,
                autoWidth = TRUE,
                scrollX = TRUE,
                fixedColumns = list(leftColumns = 1)
              )
          ) %>% 
              formatPercentage(c('TS%',"2FG%", "3FG%", "FT%"), 1) %>% 
              formatRound(c(5:15), 2)

```